services:
  kafka:
    image: bitnami/kafka:latest
    volumes:
      - ./kafka:/bitnami/kafka
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--bootstrap-server=kafka:9092", "--list"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 15s

  init-kafka:
    image: bitnami/kafka:latest
    working_dir: /opt/bitnami/kafka/bin
    entrypoint: /bin/sh
    depends_on:
      kafka:
        condition: service_healthy
    command: kafka-topics.sh --create --if-not-exists --topic chat-messages --replication-factor=1 --partitions=3 --bootstrap-server kafka:9092

  cassandra:
    image: cassandra:latest
    volumes:
      - ./cassandra:/var/lib/cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra-load-keyspace:
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./cassandra/init_cassandra.cql:/init_cassandra.cql
    command: ["sh", "-c", "cqlsh cassandra -f /init_cassandra.cql"]

  app:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      cassandra:
        condition: service_healthy
      kafka:
        condition: service_started
